class PageName:
    PAGE_PV_LOGIN = "PAGE_PV_LOGIN"
    
    PAGE_HOME = "PAGE_HOME"
    
    PAGE_CAFE = "PAGE_CAFE"
    
    PAGE_TIMETABLE = "PAGE_TIMETABLE"
    PAGE_TIMETABLE_SEL = "PAGE_TIMETABLE_SEL"
    
    PAGE_CLUB = "PAGE_CLUB"
    
    PAGE_CRAFT = "PAGE_CRAFT"
    PAGE_CRAFT_SELECT = "PAGE_CRAFT_SELECT"
    PAGE_CRAFT_FINISH = "PAGE_CRAFT_FINISH"
    
    PAGE_FIGHT_CENTER = "PAGE_FIGHT_CENTER"
    
    PAGE_WANTED = "PAGE_WANTED"
    PAGE_WANTED_1 = "PAGE_WANTED_1"
    PAGE_WANTED_2 = "PAGE_WANTED_2"
    PAGE_WANTED_3 = "PAGE_WANTED_3"
    
    PAGE_EXCHANGE = "PAGE_EXCHANGE"
    PAGE_EXCHANGE_1 = "PAGE_EXCHANGE_1"
    PAGE_EXCHANGE_2 = "PAGE_EXCHANGE_2"
    PAGE_ENCHANGE_3 = "PAGE_ENCHANGE_3"
    
    PAGE_CONTEST = "PAGE_CONTEST"
    
    PAGE_EDIT_TEAM = "PAGE_EDIT_TEAM"
    
    PAGE_TASK_CENTER = "PAGE_TASK_CENTER"
    
    PAGE_LOADING = "PAGE_LOADING"
    
    PAGE_MAILBOX = "PAGE_MAILBOX"


    